tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "isen-ng/dotnet-sdk-versions"
brew "antidote"
brew "fzf"
brew "starship"
brew "volta"
brew "yadm"
brew "zoxide"
cask "dotnet-sdk6-0-100"
cask "dotnet-sdk6-0-400"
cask "font-fira-code-nerd-font"
cask "web storm"
cask "visual-studio-code"
